const players = [
  { "id": "p1", "name": "Knogs#RK1", "tier": "다이아4", "mainRole": "탑", "subRole": ["원딜"], "memo": "" },
  { "id": "p2", "name": "각보기#KR1", "tier": "다이아4", "mainRole": "정글", "subRole": ["서폿"], "memo": "" },
  { "id": "p3", "name": "우월해#KR1", "tier": "마스터", "mainRole": "미드", "subRole": ["탑"], "memo": "" },
  { "id": "p4", "name": "통통튀는통바지#kr2", "tier": "마스터", "mainRole": "미드", "subRole": ["탑"], "memo": "" },
  { "id": "p5", "name": "사차원의벽#kr1", "tier": "다이아2", "mainRole": "정글", "subRole": ["탑", "서폿"], "memo": "" },
  { "id": "p6", "name": "빈 교#0818", "tier": "마스터", "mainRole": "원딜", "subRole": ["탑"], "memo": "" },
  { "id": "p7", "name": "녹차맛바위게#KR1", "tier": "에메랄드4", "mainRole": "서폿", "subRole": ["원딜", "탑"], "memo": "" },
  { "id": "p8", "name": "내화면은회색#KR1", "tier": "마스터", "mainRole": "탑", "subRole": ["정글"], "memo": "" },
  { "id": "p9", "name": "민 솔#KR1", "tier": "에메랄드3", "mainRole": "탑", "subRole": ["미드", "원딜"], "memo": "" },
  { "id": "p10", "name": "이판은못이겨요#KR1", "tier": "에메랄드3", "mainRole": "탑", "subRole": ["정글"], "memo": "" },
  { "id": "p11", "name": "벼룩시장#KR1", "tier": "마스터", "mainRole": "서폿", "subRole": ["정글"], "memo": "" },
  { "id": "p12", "name": "성 룡#CN1", "tier": "다이아1", "mainRole": "원딜", "subRole": [], "memo": "" },
  { "id": "p13", "name": "주도권없는미드는재앙이다#KOR", "tier": "플레티넘3", "mainRole": "탑", "subRole": ["정글"], "memo": "" },
  { "id": "p14", "name": "건우비빔밥#KR1", "tier": "마스터", "mainRole": "미드", "subRole": ["탑"], "memo": "" },
  { "id": "p15", "name": "시나래#YUK", "tier": "에메랄드4", "mainRole": "탑", "subRole": ["서폿"], "memo": "" },
  { "id": "p16", "name": "운없어나만#KR1", "tier": "에메랄드4", "mainRole": "정글", "subRole": ["탑", "서폿"], "memo": "" },
  { "id": "p17", "name": "언행이온화한사람#KR1", "tier": "다이아4", "mainRole": "탑", "subRole": ["미드"], "memo": "(탑챔프로)" },
  { "id": "p18", "name": "응애밖에할줄모름#KR1", "tier": "플레티넘3", "mainRole": "서폿", "subRole": ["원딜", "탑"], "memo": "" },
  { "id": "p19", "name": "Nodejs#isFun", "tier": "에메랄드4", "mainRole": "정글", "subRole": ["서폿", "미드"], "memo": "" },
  { "id": "p20", "name": "Joonseong#KR1", "tier": "에메랄드4", "mainRole": "서폿", "subRole": ["미드", "원딜"], "memo": "" },
  { "id": "p21", "name": "Heyesir38#kr2", "tier": "다이아4", "mainRole": "정글", "subRole": ["탑"], "memo": "" },
  { "id": "p22", "name": "머효#kr1", "tier": "플레티넘3", "mainRole": "정글", "subRole": ["미드"], "memo": "" },
  { "id": "p23", "name": "힝힝하다#KR1", "tier": "에메랄드3", "mainRole": "원딜", "subRole": ["탑"], "memo": "" },
  { "id": "p24", "name": "엄민규#KR4", "tier": "챌린저", "mainRole": "탑", "subRole": ["정글"], "memo": "" },
  { "id": "p25", "name": "누커계의샛별#KR1", "tier": "마스터", "mainRole": "원딜", "subRole": ["미드"], "memo": "" },
  { "id": "p26", "name": "보리#2018", "tier": "에메랄드4", "mainRole": "서폿", "subRole": ["정글"], "memo": "" },
  { "id": "p27", "name": "소란비#KR1", "tier": "다이아3", "mainRole": "정글", "subRole": ["원딜", "서폿"], "memo": "" },
  { "id": "p28", "name": "신희정#KR1", "tier": "에메랄드4", "mainRole": "정글", "subRole": ["탑", "서폿"], "memo": "" },
  { "id": "p29", "name": "메 샤#KR1", "tier": "마스터", "mainRole": "원딜", "subRole": ["정글"], "memo": "" },
  { "id": "p30", "name": "뮌 봉#KR1", "tier": "마스터", "mainRole": "미드", "subRole": ["탑"], "memo": "" },
  { "id": "p31", "name": "꿀벌 히나#KR1", "tier": "에메랄드2", "mainRole": "탑", "subRole": ["서폿"], "memo": "" },
  { "id": "p32", "name": "새 벽#루 나", "tier": "다이아3", "mainRole": "정글", "subRole": ["원딜", "서폿"], "memo": "" },
  { "id": "p33", "name": "zzackzzack#KR1", "tier": "다이아4", "mainRole": "미드", "subRole": ["원딜"], "memo": "" },
  { "id": "p34", "name": "하이욤헬로#KR1", "tier": "마스터", "mainRole": "서폿", "subRole": ["정글"], "memo": "" },
  { "id": "p35", "name": "물냉오이빼고#KR1", "tier": "다이아3", "mainRole": "원딜", "subRole": ["정글"], "memo": "" },
  { "id": "p36", "name": "서구리#9292", "tier": "마스터", "mainRole": "서폿", "subRole": ["원딜"], "memo": "140" },
  { "id": "p37", "name": "껄룩스#KR1", "tier": "플레티넘1", "mainRole": "정글", "subRole": ["서폿"], "memo": "" },
  { "id": "p38", "name": "이도헌원딜계정#kr1", "tier": "마스터", "mainRole": "정글", "subRole": ["원딜"], "memo": "" },
  { "id": "p39", "name": "Superplay#0915", "tier": "마스터", "mainRole": "미드", "subRole": ["탑"], "memo": "" },
  { "id": "p40", "name": "So Far So Good#KR0", "tier": "에메랄드4", "mainRole": "탑", "subRole": ["원딜", "미드"], "memo": "" },
  { "id": "p41", "name": "코 카#9124", "tier": "다이아1", "mainRole": "원딜", "subRole": ["정글"], "memo": "" },
  { "id": "p42", "name": "ATM dalu#KR1", "tier": "마스터", "mainRole": "미드", "subRole": ["서폿"], "memo": "" },
  { "id": "p43", "name": "뭔 봉#KR1", "tier": "에메랄드4", "mainRole": "서폿", "subRole": ["탑"], "memo": "" },
  { "id": "p44", "name": "공보빵#KR1", "tier": "에메랄드4", "mainRole": "서폿", "subRole": [], "memo": "전라인 가능" },
  { "id": "p45", "name": "Thantos3#KR1", "tier": "에메랄드2", "mainRole": "원딜", "subRole": [], "memo": "" }
]

export default players;
